# 端口配置
server:
  port: 80
# 数据库相关的信息配置 TODO
spring:
  application:
    name: MessageCenter
  datasource:
    url: jdbc:mysql://localhost:3306/msg_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver