##################### server-port properties #####################
server:
  port: 8888
  # 优雅停机
  shutdown: graceful

##################### database properties ######################
spring:
  application:
    name: MessageCenter
  datasource:
    url: jdbc:mysql://localhost:3306/msg_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
  # kafka相关的信息配置
  kafka:
    bootstrap-servers: 192.168.156.128:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto:
        offset:
          reset: earliest
      auto-commit-interval: 1000
      enable-auto-commit: true
  # redis 相关配置
  redis:
    host: 192.168.156.128
    port: 6379
    password: 123456
  # 项目用的是kafka但集成了rabbitmq(会自动连接),所以此处排除掉 需要使用rabbitmq时需要将其去掉
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

##################### mybatis-plus properties #####################
mybatis-plus:
  mapper-locations: classpath:/com/imwj/msg/support/dao/xml/*.xml
  type-aliases-package: com.imwj.msg.web
  global-config:
    banner: false
    db-config:
      id-type: UUID
      table-underline: true
    mapper-registry-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

##################### HTTP properties #####################
ok:
  http:
    connect-timeout: 30
    keep-alive-duration: 300
    max-idle-connections: 200
    read-timeout: 30
    write-timeout: 30

##################### apollo properties #####################
app:
  id: MessageCenter
apollo:
  bootstrap:
    enabled: ${msg.apollo.enabled}
    namespaces: message.center,dynamic-tp-apollo-dtp.yml

##################### xxl-job properties #####################
xxl:
  job:
    admin:
      addresses: http://192.168.156.128:8899/xxl-job-admin # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      username: admin # 后台用户名
      password: 123456 # 后台密码
    executor:
      appname: messageCenter # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      jobHandlerName: msgCenterJob # 执行器任务名
      ip: # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 6666 # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath: logs/xxl# 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
    accessToken:  # 执行器通讯TOKEN [选填]：非空时启用；

##################### monitor properties #####################
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

##################### msgCenter properties #####################
msg:
  business:
    topic:
      name: MESSAGE_CENTER
    grayLogIp: 192.168.156.128
    upload:
      path: e:/upload
    log:
      topic:
        name: MESSAGE_LOG
    recall:
      topic:
        name: MESSAGE_RECALL
      group:
        name: RECALL_GROUP_ID
    tagId:
      key: kafka_tag_id
      value: io.imwj.msg
  async:
    task:
      thread-name-prefix: "async-task-" # task前缀名
      max-size: 8 #最大线程数
      core-size: 4 #核心线程数
      queue-capacity: 100
      keep-alive: 60
      rejected-handler: callrunspolicy #拒绝策略,不能自定义
      allow-core-thread-timeout: true # 是否允许核心线程超时,默认false
      await-termination-seconds: 10 #
      wait-for-tasks-to-complete-on-shut-down: true # 任务执行完,在关闭应用
  xxl-job:
    enabled: true #是否开启xxljob服务
  apollo:
    enabled: true #是否开启apollo服务
  mq:
    pipeline: kafka #mq消息总线：eventbus、kafka、rocketMq
  nacos:
    enabled: true
    server: 192.168.156.128
    group: DEFAULT_GROUP
    dataId: message_center
    namespace: e085b488-eeb9-43a1-9d07-73135969a0af

##################### nacos properties #####################
nacos:
  config:
    enabled: ${msg.nacos.enabled}

##################### Rabbit properties #####################
# #RabbitMq所在服务器IP
# spring.rabbitmq.host=127.0.0.1
# #连接端口号
# spring.rabbitmq.port=5672
# #用户名
# spring.rabbitmq.username=root
# #用户密码
# spring.rabbitmq.password=123456
# # 开启发送确认
# spring.rabbitmq.publisher-confirm-type=correlated
# # 开启发送失败退回
# spring.rabbitmq.publisher-returns=true
# spring.rabbitmq.virtual-host=/
# austin.rabbitmq.topic.name=msgRabbit
# austin.rabbitmq.exchange.name=msgExchange

##################### rocketmq properties #####################
# msg-rocketmq-nameserver-ip=127.0.0.1
# msg-rocketmq-nameserver-port=9876
# msg-rocketmq-producer-group=unique-producer-group
# msg-rocketmq-biz-consumer-group=unique-biz-consumer-group
# msg-rocketmq-recall-consumer-group=unique-recall-consumer-group